;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Apr 10 2023
; Processor: AT89C51
; Compiler:  ASEM-51 (Proteus)
;====================================================================

$NOMOD51
$INCLUDE (8051.MCU)

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      org   0000h
      jmp   Start
      
;====================================================================
; CODE SEGMENT
;====================================================================

      org   0100h
Start:	
     MOV P0, #0FFH
      MOV P1, #0FFH
      MOV P2, #0FFH
      MOV P3, #0FFH
      MOV A,P0 
      MOV R1,#8
      MOV R2,#2
      MOV R3,#10
Loop:	
BATLED: 
      mov P0,#00h
      mov P1,#00h
      mov P2,#00h
      mov P3,#00h
      
      LCALL DELAY
      
      mov P0,#0FFh
      mov P1,#0FFh
      mov P2,#0FFh
      mov P3,#0FFh
      
      LCALL DELAY
      DJNZ R2,BATLED
      MOV R2,#2
      CLR C
      
DAUTIEN:
      RLC A
      MOV P0,A
      LCALL DELAY
      DJNZ R1,DAUTIEN
      
      MOV R1,#8
      MOV A,P2
      CLR C
THUHAI:  
      MOV P0,#0FFH
      
      RLC A
      MOV P2,A
      LCALL DELAY
      DJNZ R1,THUHAI
      
      MOV R1,#8
      MOV A,P3
      CLR C
      
      MOV P2,#0FFH

THUBA:
      RLC A
      MOV P3,A
      LCALL DELAY
      DJNZ R1,THUBA
      
      MOV R1,#8
      MOV A,P1
      CLR C

THUTU:
      MOV P3,#0FFH
      RLC A
      MOV P1,A
      LCALL DELAY
      DJNZ R1,THUTU
      
      MOV R1,#8
      MOV A,P0
      CLR C
      MOV P1,#0FFH
 ;done mode 1 nha
 
MODEHAI:

      MOV P1,#0AAH
      MOV P2,#0AAH
      MOV P3,#0AAH
      MOV P0,#0AAH
      
      LCALL DELAY
      LCALL DELAY
      
      MOV P1,#055H
      MOV P2,#055H
      MOV P3,#055H
      MOV P0,#055H
      
      LCALL DELAY
      LCALL DELAY
    
      DJNZ R3,MODEHAI
      MOV R3,#10
      CLR C
; MODE HAI
MODEBA: 
      MOV P1,#000H
      MOV P2,#000H
      MOV P3,#000H
      MOV P0,#000H
      
      MOV A, P0
      MOV R2, P0
    
THUNHATNHAT:
      CLR C
      MOV P0,A
      LCALL DELAY
      RLC A
      ADD A,#001H
      
      DJNZ R1,THUNHATNHAT
      MOV R1,#8
      CLR C
      
      MOV P0,#0FFH
      

      
      MOV A, P2
      ADDC A,#001H
   
      
THUHAIHAI:
      CLR C
      MOV P2,A
      LCALL DELAY
      RLC A
      ADDC A,#001H
    
      
      DJNZ R1,THUHAIHAI
      MOV R1,#8
      CLR C
      
      MOV P2,#0FFH
      
       MOV P1,#000H
     
      MOV P3,#000H
      
      MOV A, P3
      ADDC A,#001H
THUBABA:
      CLR C
      MOV P3,A
      LCALL DELAY
      RLC A
      ADDC A,#001H
      
      DJNZ R1,THUBABA
      MOV R1,#8
      CLR C
      
      MOV P3,#0FFH
     
      MOV P1,#000H
      MOV A, P1
      
     ADDC A,#001H
THUTUTU:
      CLR C
      MOV P1,A
      LCALL DELAY
      RLC A
      ADDC A,#001H
      
      DJNZ R1,THUTUTU
      MOV R1,#8
      CLR C
      MOV P1,#0FFH
; DONEMODETHU3 NHA

      
DELAY: MOV R5, #0FFH ; Load R5 with 0xF
      LOOP1: MOV R4, #0FFH ; Load R4 with 0xFF
      LOOP2: DJNZ R4, LOOP2 ; Decrement R4 and jump if not zero
       DJNZ R5, LOOP1 ; Decrement R5 and jump if not zero
       RET            ; Return to main program
;====================================================================
      END
